version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: cloudstore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloudstore
    ports:
      - "3307:3306"